### ISSUE TITLE
Fixtures seems to have issue with aggregate fields as Id

### ISSUE THREAD

**Issue by mikeSimonson** [doctrine/DoctrineFixturesBundle#107]
Everything works perfectly as long as I have an id as primary key.
Like this 

``` php
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
```

But If I want my primary key to be the composed of the date and the servername.
I get the "Object of class DateTime could not be converted to string" error.
My entity

``` php
class MyEntity
{
    /**
     * @var ProxyServer;
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="Server")
     */
    private $servername;

    /**
     * @var date
     * @ORM\Id
     * @ORM\Column(name="date", type="date", nullable=false)
     */
    private $date;
}
```

My fixtures

``` yml
model: MyEntity
tags: [ test, dev ] # optional parameter
save_in_reverse: false # optional parameter
persistence: orm # lets you choose if these fixtures should be saved through the orm or through mongodb.
fixtures:
    pt-d-1:
        servername: ps-1
        date: "-1 day"
```

Any idea where that problem come from ?
