### ISSUE TITLE
Detecting --apend flag

### ISSUE THREAD

**Issue by Invis1ble** [doctrine/DoctrineFixturesBundle#188]
I want to delete some images when `doctrine:fixtures:load` executes without `--apend` flag.
How can I detect this usecase? Is there any event or something?

**Comment by Invis1ble** [comment]
The solution is to use listeners. First, define listener as a service:
```yml
app.event_listener.console.doctrine_fixtures_load_listener:
    class: AppBundle\EventListener\Console\DoctrineFixturesLoadListener
    tags:
        - { name: kernel.event_listener, event: console.terminate }
```
Then check passed `event` object:
```php
class DoctrineFixturesLoadListener
{
    public function onConsoleTerminate(ConsoleTerminateEvent $event)
    {
        if ('doctrine:fixtures:load' === $event->getCommand()->getName() &&
            false === $event->getInput()->getOption('append') &&
            0 === $event->getExitCode()
        ) {
            // some code
        }
    }
}
```
