### ISSUE TITLE
 Class not found error with composer no-dev

### ISSUE THREAD

**Issue by wuethrich44** [doctrine/DoctrineFixturesBundle#225]
I installed this bundle as recommended as a composer dev dependency. For my production deployment I do a `composer install --optimize-autoloader --no-dev ` and this bundle gets removed.

`composer` also excute `cache:clear --no-warmup` afterwards and during that command I get this error:

```
[RuntimeException]                                                               
  An error occurred when executing the "'cache:clear --no-warmup'" command:        
  In FileLoader.php line 168:                                                      
                                                                                   
    Class AppBundle\Development\DataFixtures\CustomAbstractFixture not found in    
     /builds/app/plangate/app/config/services.yml (which is being imported from    
     "/builds/app/plangate/app/config/config.yml").                                
                                                                                   
  In BranchData.php line 11:                                                       
                                                                                   
    Class AppBundle\Development\DataFixtures\CustomAbstractFixture not found       
                                                                                   
  In CustomAbstractFixture.php line 10:                                            
                                                                                   
    Class Doctrine\Bundle\FixturesBundle\Fixture not found                         
```
The container try to autowire the fixtures but I use my fixtures only during development. 

It's a minor issue but does anybody know how I can get rid of it?

**Comment by wuethrich44** [comment]
I figured it out myself. Here is what if have done:

1. Create a `service_dev.yml` with the following content:
```yaml
services:
    # This part is important!
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Use the namespace where your fixtures are
    AppBundle\Development\DataFixtures\:
        resource: '../../src/AppBundle/Development/DataFixtures'
```
2. Import it into `config_dev.yml`
3. In your `services.yml` exclude the fixture folder:
```yaml
services:
    AppBundle\:
        exclude: '../../src/AppBundle/{Entity,Repository,Tests,Development}'
```
After these changes you can have this bundle as a dev dependency and run `composer install --optimize-autoloader --no-dev` without an error.
