### ISSUE TITLE
PDO connection error

### ISSUE THREAD

**Issue by Wokersx** [doctrine/DoctrineFixturesBundle#271]
Hello,

I work with symfony 4.2 and I use docker container for my work environment.
In my .env file, if I write 
DATABASE_URL=mysql://myusername:mypassword@**localhost**:3306/my_db, then doctrine:fixtures:load command works fine, but if I write
DATABASE_URL=mysql://myusername:mypassword@**db**:3306/my_db, then I get PDO Connection error.

Other doctrine commands works good with **db**, but doctrine:fixtures:load command gets error.
I do not use default **localhost** adress, because I run docker-compose file with service **db** (MySQL 5.7 official image).

**Comment by greg0ire** [comment]
Please provide the exact error message you are getting.

**Comment by Wokersx** [comment]
Hello @greg0ire,
hier is log with error:

```
[2018-12-31 16:38:12] console.ERROR: Error thrown while running command "doctrine:fixtures:load". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Der angegebene Host ist unbekannt. " {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Der angegebene Host ist unbekannt.  at D:\\docker-symfony-new\\web\\alex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Der angegebene Host ist unbekannt.  at D:\\docker-symfony-new\\web\\alex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Der angegebene Host ist unbekannt.  at D:\\docker-symfony-new\\web\\alex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:27, PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Der angegebene Host ist unbekannt.  at D:\\docker-symfony-new\\web\\alex_project\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:27)","command":"doctrine:fixtures:load","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Der angegebene Host ist unbekannt. "} []
[2018-12-31 16:38:12] console.DEBUG: Command "doctrine:fixtures:load" exited with code "1" {"command":"doctrine:fixtures:load","code":1} []
```

**Comment by greg0ire** [comment]
> php_network_getaddresses: getaddrinfo failed: Der angegebene Host ist unbekannt.

Something is off though… the message is in German, which makes me suspect you are not running the command on your container

**Comment by Wokersx** [comment]
It's my docker-compose.yml
```
version: '2'

services:
    webserver:
        build: ./web
        image: web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./web/alex_project:/var/www/html
            - /var/www/html/vendor
            - ./apache-log:/var/log/apache2
        links:
            - db

    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql
            # - ./database.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            - MYSQL_ROOT_PASSWORD=mypassword
            - MYSQL_DATABASE=my_db
```
You are right. I run this command **doctrine:fixtures:load** in terminal (windows PowerShell on my local machine) 🤣 
I try to use docker only for development environment
