### ISSUE TITLE
Fixtures are loaded by their class name but registered as service and get overwritten.

### ISSUE THREAD

**Issue by Bavragor** [doctrine/DoctrineFixturesBundle#279]
E.g. you want to use a fixture like a factory and define its loaded stuff by arguments given.
You can't register the same class multiple times because get_class is used instead of service id.

Could be fixed in Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader Line 36 by using service id as array key instead of get_class.

Should I open a PR for this?

**Comment by alcaeus** [comment]
I'm not sure I understand, can you show an example please?

**Comment by Bavragor** [comment]
I have a fixture class which does stuff based on constructor arguments and differs by its groups e.g. one implementation handles object fixtures and another one handles user fixtures.

Now I don't want to implement two empty classes that extend this fixture class which are only different by service configuration and their injected constructor arguments, but I'm kinda forced to because fixtures are registered in SymfonyFixtureLoader by their class and not their service id.

My configuration could look like this, but then the last registered class of product\App\DataFixtures\Alice\AliceFixturesLoader would be the only one that gets loaded:
```
  product.doctrine.fixtures.loader.alice:
    class: product\App\DataFixtures\Alice\AliceFixturesLoader
    arguments:
      - '@product.alice_loader.doctrine_orm_loader'
      - '@kernel'
      - '@doctrine.orm.default_entity_manager'
      - '%env(APP_ENV)%'
  product.doctrine.fixtures.loader.alice.grouped.user:
    parent: 'product.doctrine.fixtures.loader.alice'
    arguments:
      - ['product\Cmdb\BasicCategories\DataFixtures\ObjectClassificationFixtures']
      - ['user', 'user_role']
    tags:
      - { name: !php/const Doctrine\Bundle\FixturesBundle\DependencyInjection\CompilerPass\FixturesCompilerPass::FIXTURE_TAG, group: 'user'}
      - { name: !php/const Doctrine\Bundle\FixturesBundle\DependencyInjection\CompilerPass\FixturesCompilerPass::FIXTURE_TAG, group: 'user_role'}
  product.doctrine.fixtures.loader.alice.grouped.object:
    parent: 'product.doctrine.fixtures.loader.alice'
    arguments:
      - ['product\Cmdb\BasicCategories\DataFixtures\ObjectClassificationFixtures']
      - ['object']
    tags:
      - { name: !php/const Doctrine\Bundle\FixturesBundle\DependencyInjection\CompilerPass\FixturesCompilerPass::FIXTURE_TAG, group: 'object'}
```
