### ISSUE TITLE
How to add table prefix when I use  doctrine:fixtures:load 

### ISSUE THREAD

**Issue by emass293** [doctrine/DoctrineFixturesBundle#293]
I have a service like 
```yaml
 App\Doctrine\TableSchema:
        arguments:
            $prefix: '%env(string:DATABASE_PREFIX)%'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
```
This service works welle width the command 'doctrine:schema:create'
