### ISSUE TITLE
Connection charset not applied when loading fixtures

### ISSUE THREAD

**Issue by nzurita** [doctrine/DoctrineFixturesBundle#314]
In Symfony 4.4, I have a fixture load class, and execute it via `bin/console doctrine:fixtures:load --append`. The values loaded in database are incorrectly encoded.

The database and tables are UTF8. The text file containing the loader is also UTF8 encoded, the connection is supposed to be configured as UTF8 (maybe the syntax for this changed in latter versions?).

These are some relevant parts of my code:

**The string in the loader script (note the euro symbol):**
```
$documentContent = [ 'content' => 'Lorem ipsum CONTRACT_AMOUNT% €'];
```
**File config/packages/doctrine.yaml:**
```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: "utf8"
```
**Values in database:**

> Lorem ipsum %CONTRACT_AMOUNT% �
